name: Build and deploy it

on:
  push:
    branches:
      - main

env:
  URL: abschlusstagung.intia.de

jobs:
  build-test:
    runs-on: ubuntu-20.04
    environment:
      name: development
      url: https://${{ env.URL }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.4.0

      - name: Using cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-v2-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-v2-

      - name: Build Site
        uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_TOKEN }}
          target_branch: "gh-pages"
